### ISSUE TITLE
Kube-hunter in cluster scans are failing

### ISSUE THREAD

**Issue by darox** [secureCodeBox/secureCodeBox#1323] opened 2022-08-28 15:37 UTC
### Describe the bug
Scan with Kube-hunter  errors with:
```
 Error Description:      Failed to run the Parser. This is likely a Bug, we would like to know about. Please open up a Issue on GitHub.
  Finding Download Link:  https://s3.damn.li/code-secure-box/scan-89381132-a887-4556-ac4e-7ef825bde8ad/findings.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sXMaHArTlJ3WAI1n%2F20220828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220828T101056Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=fdacb77256aa4be0784d62889d831905f1625e0ed2247866d60186958c8506b7
  Finding Head Link:      https://s3.damn.li/code-secure-box/scan-89381132-a887-4556-ac4e-7ef825bde8ad/findings.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sXMaHArTlJ3WAI1n%2F20220828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220828T101056Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=84f46fb7a2e9a83d5242b637e39d0dee867e99bd0eeb9b2d5609b285c1468967
  Findings:
    Severities:
  Raw Result Download Link:  https://s3.damn.li/code-secure-box/scan-89381132-a887-4556-ac4e-7ef825bde8ad/kube-hunter-results.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sXMaHArTlJ3WAI1n%2F20220828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220828T101056Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=187085ba5006afb3b8c2728c2d0a1a396e07cb43318c61d1f0218dfb76d3112b
  Raw Result File:           kube-hunter-results.json
  Raw Result Head Link:      https://s3.damn.li/code-secure-box/scan-89381132-a887-4556-ac4e-7ef825bde8ad/kube-hunter-results.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=sXMaHArTlJ3WAI1n%2F20220828%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220828T101056Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=03050a094a74fa5624e956534ee2781bccf531b60abe480dce772f1c18dc4dd9
  Raw Result Type:           kube-hunter-json
  State:                     Errored
Events:                      <none>
```

I can see the reports in my S3:
![image](https://user-images.githubusercontent.com/9934402/187082101-ebe66da7-e3ad-403a-bdcc-874c2c637696.png)

### Steps To Reproduce
1. Run a scheduled kube-hunter scan 
2. Run kubectl get scans
3. Run kuebctl describe scan kube-hunter-in-cluster-1661508655
4. Check error

### Expected behavior
Scans can be parsed and scan state is not ERRORED

### System (please complete the following information):
 - secureCodeBox Version/Release: 3.14.3
 - OS: 20.04
 - Kubernetes Version [command: v1.24.0
 - Crio: 1.23.3
 - Runc:  1.1.0-0ubuntu1~20.04.1

**Comment by J12934** [comment] 2022-09-05 14:01
Hi @darox 

tried to reprodice the error but wasn't able to.
Can you post some additional information on what you scanned and maybe even post the (anonymized) raw results / kube-hunter out put from s3? The scanner has finished but the secureCodeBox parser has crashed.

**Comment by J12934** [comment] 2022-10-26 13:00
Closing this as I can't reproduce it. If you have more information feel free to repoen 🙏

**Closed by J12934** 2022-10-26 13:00 UTC
Labels: bug
