### ISSUE TITLE
Issue with CascadingScans + DefectDojo Hook w/ Sync Back Mode

### ISSUE THREAD

**Issue by kaz-33** [secureCodeBox/secureCodeBox#2601] opened 2024-07-31 08:54 UTC
## Your Question
i test cascading feature with nmap+nikto, simple configuration regarding your example, but nothing apperare after cascading job.
I suppose i miss some configuration, but i don't see the root cause

Configuration bellow:
rulescascading description
```
Name:         nikto
Namespace:    securecodebox-system
Labels:       securecodebox.io/intensive=high
              securecodebox.io/invasive=invasive
Annotations:  <none>
API Version:  cascading.securecodebox.io/v1
Kind:         CascadingRule
Metadata:
  Creation Timestamp:  2024-07-31T08:33:28Z
  Generation:          1
  Resource Version:    141420807
  UID:                 183b46ec-1c1f-49a6-bb33-2966f5fdaf44
Spec:
  Matches:
    Any Of:
      Attributes:
        Port:    443
        State:   open
      Category:  Open Port
      Attributes:
        Service:  https
        State:    open
      Category:   Open Port
      Attributes:
        Port:    80
        State:   open
      Category:  Open Port
      Attributes:
        Service:  http
        State:    open
      Category:   Open Port
  Scan Spec:
    Resource Mode:  namespaceLocal
    Scan Type:      nikto
Events:             <none>
```

scan description
```
Name:         test-nmap-cascading
Namespace:    securecodebox-system
Labels:       <none>
Annotations:  <none>
API Version:  execution.securecodebox.io/v1
Kind:         Scan
Metadata:
  Creation Timestamp:  2024-07-31T08:33:45Z
  Finalizers:
    s3.storage.securecodebox.io
  Generation:        2
  Resource Version:  141425346
  UID:               687825be-1afe-40e0-a481-c02e52a66cbc
Spec:
  Cascades:
    Inherit Affinity:         true
    Inherit Annotations:      true
    Inherit Env:              false
    Inherit Hook Selector:    false
    Inherit Init Containers:  false
    Inherit Labels:           true
    Inherit Tolerations:      true
    Inherit Volumes:          false
    Match Labels:
      securecodebox.io/intensive:  high
      securecodebox.io/invasive:   invasive
    Scope Limiter:
      Valid On Missing Render:  false
  Parameters:
    -Pn
    -sV
    scanme.nmap.org
  Resource Mode:  namespaceLocal
  Resources:
  Scan Type:  nmap
Status:
  Finding Download Link:  https://minio.securecodebox-system.svc.cluster.local/securecodebox/scan-687825be-1afe-40e0-a481-c02e52a66cbc/findings.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=securecodebox-s3%2F20240731%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T083345Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=9bebe684a6371d1048d14c780bc06f2165454d11e987ed88308a85fffc07d141
  Finding Head Link:      https://minio.securecodebox-system.svc.cluster.local/securecodebox/scan-687825be-1afe-40e0-a481-c02e52a66cbc/findings.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=securecodebox-s3%2F20240731%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T083345Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=a4a70e90ad3e2ef096d9d47432cf15b4f58e820a12cbc1542eba45fcc5512ff3
  Findings:
    Categories:
      Host:       1
      Open Port:  8
    Count:        9
    Severities:
      Informational:  9
  Ordered Hook Statuses:
    [map[hookName:defectdojo-persistence-defectdojo jobName:defectdojo-persistence-defectdojo-test-nmap-cascading-9vqkw priority:0 state:Completed type:ReadAndWrite]]
    [map[hookName:cascading-scans jobName:cascading-scans-test-nmap-cascading-vjl64 priority:0 state:Completed type:ReadOnly]]
  Raw Result Download Link:  https://minio.securecodebox-system.svc.cluster.local/securecodebox/scan-687825be-1afe-40e0-a481-c02e52a66cbc/nmap-results.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=securecodebox-s3%2F20240731%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T083345Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d91a3335581738548d3033dc6f812b29c8c86098e203921165072f0efc74383e
  Raw Result File:           nmap-results.xml
  Raw Result Head Link:      https://minio.securecodebox-system.svc.cluster.local/securecodebox/scan-687825be-1afe-40e0-a481-c02e52a66cbc/nmap-results.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=securecodebox-s3%2F20240731%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240731T083345Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=14437006541025bf3946b7c1be9917b877aa1cd1babaf19db51db76cdba3d152
  Raw Result Type:           nmap-xml
  State:                     Done
Events:                      <none>
```
logs scan:

```
Defaulted container "nmap" out of: nmap, lurker
Starting Nmap 7.95 ( https://nmap.org ) at 2024-07-31 08:34 UTC
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.16s latency).
Other addresses for scanme.nmap.org (not scanned): 2600:3c01::f03c:91ff:fe18:bb2f
Not shown: 992 closed tcp ports (conn-refused)
PORT      STATE    SERVICE      VERSION
22/tcp    open     ssh          OpenSSH 6.6.1p1 Ubuntu 2ubuntu2.13 (Ubuntu Linux; protocol 2.0)
80/tcp    open     http         Apache httpd 2.4.7 ((Ubuntu))
389/tcp   filtered ldap
445/tcp   filtered microsoft-ds
2000/tcp  open     tcpwrapped
5060/tcp  open     tcpwrapped
9929/tcp  open     nping-echo   Nping echo
31337/tcp open     tcpwrapped
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 22.12 seconds
```

logs cascading
```
Starting hook for Scan "test-nmap-cascading"
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Fetched 6 findings from the file storage
Fetching CascadingScans using LabelSelector: "securecodebox.io/intensive=high,securecodebox.io/invasive=invasive"
Fetched 1 CascadingRules
Hook completed
```

the pod in cascade joins the defectdojo but after nothing... I wait for the scan with nikto on port 80...but nothing appears, an idea ?

**Comment by Weltraumschaf** [comment] 2024-07-31 09:26
Hi @kaz-33 ,

thanks for submitting this question. We'll investigate this.

**Comment by kaz-33** [comment] 2024-08-07 09:52
Hi Teams,
any update?
Thx for your help.
Br

**Comment by J12934** [comment] 2024-08-08 08:05
Hi,
Yup looks weird at least the nmap logs indicate that the port 80 should have been found and the rule should have triggered.

Something which is definitly off / wrong is that the cascading rule seems to be missing the parameters so the nikto scan would be invalid as it wouldn't have any parameters.

If you can also post the finding.json that would also help to be able to look at the parsed results.
You can also have a look at the cascading rule that we have written for nikto, that should work: https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/nikto/cascading-rules/http.yaml

**Comment by kaz-33** [comment] 2024-08-08 08:58
finding.json files below

```
[{"id":"ed925334-175c-45c4-8008-1051d62056d2","name":"Open Port: 2000/TCP","location":"tcp://scanme.nmap.org:2000","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 2000/tcp\n\n\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":93,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/93","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":83,"duplicate":true,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":{"id":"4c59717f-e873-47e1-aa0e-82a29c0887df","name":"Open Port: 2000/TCP","location":"tcp://scanme.nmap.org:2000","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 2000/tcp\n\n\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":83,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/83","defectdojo.org/test-id":22,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/22","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T07:29:53.163932Z","identified_at":null}},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.712340Z","identified_at":null},{"id":"464ef3d0-69d9-4671-9592-fd6bab197a99","name":"Open Port: 22/TCP","location":"tcp://scanme.nmap.org:22","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 22/tcp\n\n\n**Product:** OpenSSH\n**Version:** 6.6.1p1 Ubuntu 2ubuntu2.13\n**Extra Info:** Ubuntu Linux; protocol 2.0\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":91,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/91","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":85,"duplicate":true,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":{"id":"352c85f2-f0e7-4b6e-a238-eeb3987f4bb7","name":"Open Port: 22/TCP","location":"tcp://scanme.nmap.org:22","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 22/tcp\n\n\n**Product:** OpenSSH\n**Version:** 6.6.1p1 Ubuntu 2ubuntu2.13\n**Extra Info:** Ubuntu Linux; protocol 2.0\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":85,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/85","defectdojo.org/test-id":23,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/23","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T07:35:56.167134Z","identified_at":null}},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.566908Z","identified_at":null},{"id":"d8a92674-30c0-4a60-8d8f-b5e45619c337","name":"Open Port: 31337/TCP","location":"tcp://scanme.nmap.org:31337","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 31337/tcp\n\n\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":96,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/96","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.905905Z","identified_at":null},{"id":"2ce84cfb-e4f0-49e8-82d2-6428d6c5586a","name":"Open Port: 5060/TCP","location":"tcp://scanme.nmap.org:5060","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 5060/tcp\n\n\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":94,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/94","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.773633Z","identified_at":null},{"id":"dd5392f6-d3f4-4878-8aa5-ad67da685a8b","name":"Open Port: 80/TCP","location":"tcp://scanme.nmap.org:80","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 80/tcp\n\n\n**Product:** Apache httpd\n**Version:** 2.4.7\n**Extra Info:** (Ubuntu)\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":92,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/92","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":86,"duplicate":true,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":{"id":"92156434-7ed0-45e4-9d3f-d2b43c450d2f","name":"Open Port: 80/TCP","location":"tcp://scanme.nmap.org:80","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 80/tcp\n\n\n**Product:** Apache httpd\n**Version:** 2.4.7\n**Extra Info:** (Ubuntu)\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":86,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/86","defectdojo.org/test-id":23,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/23","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T07:35:56.266822Z","identified_at":null}},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.650012Z","identified_at":null},{"id":"042b1a85-942e-4ba1-a9d2-84af9a2cc6ca","name":"Open Port: 9929/TCP","location":"tcp://scanme.nmap.org:9929","description":"### Host\n\n**IP Address:** 45.33.32.156\n**FQDN:** scanme.nmap.org\n\n\n**Port/Protocol:** 9929/tcp\n\n\n**Product:** Nping echo\n\n\n","category":"DefectDojo Imported Finding","severity":"INFORMATIONAL","attributes":{"defectdojo.org/finding-id":95,"defectdojo.org/finding-url":"http://10.4.8.28:8080/finding/95","defectdojo.org/test-id":24,"falsePositive":false,"defectdojo.org/test-url":"http://10.4.8.28:8080/test/24","defectdojo.org/original-finding-id":null,"duplicate":false,"riskAccepted":false,"outOfScope":false,"defectdojo.org/original-finding":null},"osi_layer":null,"parsed_at":"2024-07-31T08:36:16.839076Z","identified_at":null}]
```

**Comment by kaz-33** [comment] 2024-08-08 16:46
thx for the tricky, it's change the way to run the cascading but now i get this error
![image](https://github.com/user-attachments/assets/74addbef-6555-4a7a-acb3-81fd1a98e098)

**Comment by kaz-33** [comment] 2024-08-08 16:51
and the json file
```
[{"name":"Open Port: 22 (ssh)","description":"Port 22 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:22","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":22,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"ssh","serviceProduct":"OpenSSH","serviceVersion":"6.6.1p1 Ubuntu 2ubuntu2.13","scripts":null,"tunnel":null},"id":"47e38c72-8eb2-4963-b656-d19f3b802bed","parsed_at":"2024-08-08T16:40:21.459Z"},{"name":"Open Port: 23 (telnet)","description":"Port 23 is filtered using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:23","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":23,"state":"filtered","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"table","operating_system":null,"service":"telnet","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"56cd9eb9-d153-4a40-a44d-9267caef7010","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 80 (http)","description":"Port 80 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:80","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":80,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"http","serviceProduct":"Apache httpd","serviceVersion":"2.4.7","scripts":null,"tunnel":null},"id":"0bd993ef-cf94-4c19-87b7-0d3f02b96f5a","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 389 (ldap)","description":"Port 389 is filtered using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:389","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":389,"state":"filtered","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"table","operating_system":null,"service":"ldap","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"1d85a00c-dc2a-4ede-ac57-2bb1847371ad","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 445 (microsoft-ds)","description":"Port 445 is filtered using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:445","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":445,"state":"filtered","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"table","operating_system":null,"service":"microsoft-ds","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"5768abc2-86f7-4562-81dd-93cfd35def59","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 2000 (tcpwrapped)","description":"Port 2000 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:2000","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":2000,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"tcpwrapped","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"c1188e79-4c21-4472-aeea-640460041c8c","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 5060 (tcpwrapped)","description":"Port 5060 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:5060","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":5060,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"tcpwrapped","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"3d698138-3746-4195-a737-78ed0a0ae823","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 9929 (nping-echo)","description":"Port 9929 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:9929","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":9929,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"nping-echo","serviceProduct":"Nping echo","serviceVersion":null,"scripts":null,"tunnel":null},"id":"334113fa-d0a1-4e03-916f-6d390bc3b1c8","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Open Port: 31337 (tcpwrapped)","description":"Port 31337 is open using tcp protocol.","category":"Open Port","location":"tcp://scanme.nmap.org:31337","osi_layer":"NETWORK","severity":"INFORMATIONAL","attributes":{"port":31337,"state":"open","ip_addresses":["45.33.32.156"],"mac_address":null,"protocol":"tcp","hostname":"scanme.nmap.org","method":"probed","operating_system":null,"service":"tcpwrapped","serviceProduct":null,"serviceVersion":null,"scripts":null,"tunnel":null},"id":"1d0dfcf2-195c-4dca-b638-8eb8083bf3aa","parsed_at":"2024-08-08T16:40:21.460Z"},{"name":"Host: scanme.nmap.org","category":"Host","description":"Found a host","location":"scanme.nmap.org","severity":"INFORMATIONAL","osi_layer":"NETWORK","attributes":{"ip_addresses":["45.33.32.156"],"hostname":"scanme.nmap.org","operating_system":null},"id":"619e5485-1fda-4095-8f53-2d2e2cfc20a5","parsed_at":"2024-08-08T16:40:21.460Z"}]
```

**Comment by J12934** [comment] 2024-08-09 07:13
This is very likely caused by your CascadingRule missing the parameters, see my earlier comment: https://github.com/secureCodeBox/secureCodeBox/issues/2601#issuecomment-2275204887
The null pointer shouldn't have happened though, i thought the parameters were marked as required. Will have a look if we can ensure that these are always set.

I'd recommend again to refer to the nikto cascading rule i linked as the have the nikto params defined with the proper templates and also take care of configuring nikto properly if the identified target is running with a non default http(s) ports.

**Comment by kaz-33** [comment] 2024-08-09 07:40
Thx, but the issue seems to be more global, i try with ssh cascading
```
Name:         sshaudit
Namespace:    securecodebox-system
Labels:       securecodebox.io/intensive=high
              securecodebox.io/invasive=invasive
Annotations:  <none>
API Version:  cascading.securecodebox.io/v1
Kind:         CascadingRule
Metadata:
  Creation Timestamp:  2024-08-09T07:31:30Z
  Generation:          1
  Resource Version:    157424268
  UID:                 c1445f71-b8e2-410a-8353-c3dc97c96d31
Spec:
  Matches:
    Any Of:
      Attributes:
        Port:    22
        State:   open
      Category:  Open Port
      Attributes:
        Service:  ssh
        State:    open
      Category:   Open Port
  Scan Spec:
    Resource Mode:  namespaceLocal
    Scan Type:      ssh-audit
Events:             <none>
```
and the issue is the same
```
cascading-scans-nmapcascading-tt6gf-vc2xc hook Fetched 11 findings from the file storage
cascading-scans-nmapcascading-tt6gf-vc2xc hook Fetching CascadingScans using LabelSelector: "securecodebox.io/intensive=high,securecodebox.io/invasive=invasive"
cascading-scans-nmapcascading-tt6gf-vc2xc hook Fetched 1 CascadingRules
cascading-scans-nmapcascading-tt6gf-vc2xc hook Error was thrown while running hooks handle function
cascading-scans-nmapcascading-tt6gf-vc2xc hook TypeError: Cannot read properties of undefined (reading 'map')
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at templateCascadingRule (/home/app/hook-wrapper/hook/hook.js:317:57)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at getCascadingScan (/home/app/hook-wrapper/hook/hook.js:219:21)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at _loop_1 (/home/app/hook-wrapper/hook/hook.js:207:33)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at getScansMatchingRule (/home/app/hook-wrapper/hook/hook.js:212:9)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at getCascadingScans (/home/app/hook-wrapper/hook/hook.js:174:48)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at /home/app/hook-wrapper/hook/hook.js:109:38
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at step (/home/app/hook-wrapper/hook/hook.js:70:23)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at Object.next (/home/app/hook-wrapper/hook/hook.js:51:53)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at fulfilled (/home/app/hook-wrapper/hook/hook.js:42:58)
cascading-scans-nmapcascading-tt6gf-vc2xc hook     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by kaz-33** [comment] 2024-08-09 08:59
i found my missconfiguration

```
-> Created scan ssh-auditcascading-sshaudit-pn4cm
Hook completed
```

thx for your support

**Closed** 2024-08-09 10:01 UTC
Labels: question
