### ISSUE TITLE
"Exception while attaching findings to engagement" error in Persistence-defectdojo

### ISSUE THREAD

**Issue by danil-smirnov** [secureCodeBox/secureCodeBox#2384] opened 2024-03-18 10:20 UTC
### Describe the bug

We do the following scan by Trivy:
```
apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  name: trivy-scheduled-1710756368
  namespace: securecodebox-system
  annotations:
    defectdojo.securecodebox.io/engagement-name: Trivy weekly image scan @ 2024-03-18
    defectdojo.securecodebox.io/product-name: stage-cluster
    defectdojo.securecodebox.io/product-type-name: Infra
    defectdojo.securecodebox.io/test-title: gcp-secrets-clean-up-28509120/debian:latest
spec:
  scanType: trivy-image
  parameters:
  - debian:latest
```

Scan and parse stages go just fine. But `Persistence-defectdojo hook` has failed with an error:

```
2024-03-18 10:06:41 ERROR DefaultImportScanService:128 - Exception while attaching findings to engagement: 400 Bad Request: "{"message":"[\"Invalid URL format: expected integer for port, not 'latest'\"]"}"
2024-03-18 10:06:41 ERROR DefectDojoPersistenceProvider:30 - Failed to attach findings to engagement.
io.securecodebox.persistence.defectdojo.exception.PersistenceException: Failed to attach findings to engagement.
	at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.createFindings(DefaultImportScanService.java:129)
	at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.reimportScan(DefaultImportScanService.java:80)
	at io.securecodebox.persistence.strategies.VersionedEngagementsStrategy.run(VersionedEngagementsStrategy.java:144)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.execute(DefectDojoPersistenceProvider.java:50)
	at io.securecodebox.persistence.DefectDojoPersistenceProvider.main(DefectDojoPersistenceProvider.java:28)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"message":"[\"Invalid URL format: expected integer for port, not 'latest'\"]"}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:783)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:608)
	at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.exchangeRequest(DefaultImportScanService.java:135)
	at io.securecodebox.persistence.defectdojo.service.DefaultImportScanService.createFindings(DefaultImportScanService.java:126)
	... 4 more
```

### System (please complete the following information):

- operator-4.4.1
- trivy-4.5.0
- persistence-defectdojo-4.4.1

**Comment by Weltraumschaf** [comment] 2024-03-18 14:59
Hi @danil-smirnov,

thanks for submitting this issue. We'll investigate this.

**Comment by Weltraumschaf** [comment] 2024-03-20 10:45
This seems to be a duplicate of https://github.com/secureCodeBox/secureCodeBox/issues/2324

**Comment by danil-smirnov** [comment] 2024-03-20 11:01
Why do you think so @Weltraumschaf ? The error is completely different

**Comment by Weltraumschaf** [comment] 2024-03-20 11:20
My assumtion:
- It is the same scanner (Trivy).
- It is also malformed URL error.
- The message complains about "latest" is not a port number and use "debian:latest" in the YAML.

So, my educated guess is that the URL is something like "...debian:latest..." which is not valid.

**Comment by J12934** [comment] 2024-03-20 13:27
All of the (3 I think) recent trivy+DefectDojo issues should be fixed by the changes outlined here 😊 https://github.com/secureCodeBox/secureCodeBox/issues/2364#issuecomment-2009381947

With it the issue would not occur anymore as we'd DD handle the trivy format and it wouldn't encounter these malformed uris.

We should still fix the underlying parser for both the trivy-k8s and trivy-image types to produce valid uris though.

**Closed** 2024-06-28 09:40 UTC
Labels: bug
