### ISSUE TITLE
gitleaks: cannot use fork features

### ISSUE THREAD

**Issue by malexmave** [secureCodeBox/secureCodeBox#790] opened 2021-11-01 11:09 UTC
## 🐞 Bug report
I cannot get the secureCodeBox fork of gitleaks to work.

### Describe the bug
According to [the instructions](https://docs.securecodebox.io/docs/scanners/gitleaks#securecodebox-extended-gitleaks-features), the following commands should install the gitleaks fork that contains the `--commit-since-duration` switch that is not yet part of the main gitleaks codebase:
```bash
helm upgrade --install gitleaks secureCodeBox/gitleaks \
  --set="scanner.image.repository=docker.io/securecodebox/scanner-gitleaks" \
  --set="scanner.image.tag=v7.3.0"
```

However, if I then run a scan, the system reports that it does not know the switch.

### Steps To Reproduce
Install the gitleaks scanner as described above, then run the following scan:

```yaml
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "scan-repo"
spec:
  scanType: "gitleaks"
  parameters:
    - "--repo-url"
    - "https://github.com/secureCodeBox/secureCodeBox"
    # Apply all available rules
    - "--config-path"
    - "/home/config_all.toml"
    # Redact secrets from log messages and leaks
    - "--redact"
    # Only scan commits since the last 24h
    # (Error also occurs if you drop the =24h and place the 24h on a separate line
    - "--commit-since-duration=24h"
```

<img width="894" alt="grafik" src="https://user-images.githubusercontent.com/1688580/139662180-d2367102-25c0-4ded-ba3d-4a1f4431211e.png">

### Expected behavior
It should scan the commits in the last 24 hours.

### Additional notes
I first assumed that the mistake may be that the helm command should be as follows:
```bash
helm upgrade --install gitleaks secureCodeBox/gitleaks \
  --set="scanner.image.repository=docker.io/securecodebox/gitleaks" \  # not scanner-gitleaks
  --set="scanner.image.tag=v7.3.0"
```

However, if I use that, it fails because the image does not contain the wrapper.sh:
```
sh: can't open '/wrapper.sh': No such file or directory
```

I am unsure how the [securecodebox/gitleaks](https://hub.docker.com/r/securecodebox/gitleaks) image was built, so I cannot tell if it is just outdated and should be updated to contain the new wrapper script, or if the issue is somewhere else.

**Comment by Ilyesbdlala** [comment] 2021-11-09 16:56
> I first assumed that the mistake may be that the helm command should be as follows:
> 
> ```shell
> helm upgrade --install gitleaks secureCodeBox/gitleaks \
>   --set="scanner.image.repository=docker.io/securecodebox/gitleaks" \  # not scanner-gitleaks
>   --set="scanner.image.tag=v7.3.0"
> ```

I think you're right. it's a mistake in the documentation, because securecodebox/scanner-gitleaks is the docker image that we build from the remote gitleaks image, not from our fork ([/scanners/gitleaks/scanner/Dockerfile](https://github.com/secureCodeBox/secureCodeBox/blob/main/scanners/gitleaks/scanner/Dockerfile))

>I am unsure how the [securecodebox/gitleaks](https://hub.docker.com/r/securecodebox/gitleaks) image was built, so I cannot tell if it is just outdated and should be updated to contain the new wrapper script, or if the issue is somewhere else.
>
Updating the fork gitleaks image securecodebox/gitleaks with the following Dockerfile resolves the issue. The wrapper.sh was missing.
```Dockerfile
ARG scannerVersion=latest
FROM securecodebox/gitleaks:v7.3.0  # changed from zricethezav/gitleaks:${scannerVersion}
USER root  
COPY wrapper.sh /wrapper.sh  
RUN chmod o+x ./wrapper.sh  
#USER gitleaks  Or create a gitleaks user
ENTRYPOINT ["./wrapper.sh" ]
```
Someone with Docker Hub rights can upload this image for a temporary fix (@J12934 👀 ).
The problem is, as you mentioned, is that the image is out of date and it doesn't seem like the PR that @rseedorff created is going to be merged (zricethezav/gitleaks#498). I don't know if we can support this feature efficiently.

**Closed** 2022-03-16 16:31 UTC
Labels: bug, scanner
